core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieList.as_view(), name='movie_list'),
    path('top/ten/movies', views.TopMovies.as_view(), name='top_ten_movie'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='movie_detail'),
    path('movie/vote/<int:movie_id>/create', views.CreateVote.as_view(), name='create_vote'),
    path('movie/vote/<int:movie_id>/update/<int:pk>', views.UpdateVote.as_view(), name='update_vote'),
    path('movie/<int:movie_id>/upload/image', views.MovieImageUpload.as_view(), name='movie_image_upload')
]

mysite/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

import core.urls
import user.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from user import views


app_name = 'user'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

templates/layouts/navabar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">HenryLab</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'core:top_ten_movie' %}">Top Ten Movies</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
                  <li><a href="{% url 'core:movie_list' %}">{{ request.user.username }}</a></li>
                  <li><a href="{% url 'user:logout' %}">Signout</a></li>
                  {% else %}
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'user:register' %}">Sign up</a></li>
                  <li><a href="{% url 'user:login' %}">Sign in</a></li>
{% endif %}
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>