core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieList.as_view(), name='movie_list'),
    path('top/ten/movies', views.TopMovies.as_view(), name='top_ten_movie'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='movie_detail'),
    path('movie/vote/<int:movie_id>/create', views.CreateVote.as_view(), name='create_vote'),
    path('movie/vote/<int:movie_id>/update/<int:pk>', views.UpdateVote.as_view(), name='update_vote'),
    path('movie/<int:movie_id>/upload/image', views.MovieImageUpload.as_view(), name='movie_image_upload')
]

mysite/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

import core.urls
import user.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.contrib.auth import get_user_model
from django.db.models.aggregates import Sum
from django.db import models
from uuid import uuid4

# Custom model manager


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed', 'writing_credits', 'role_set__movie')


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


def movie_directory_path_with_uuid(instance, filename):
    return '{}/{}'.format(instance.movie_id, uuid4())


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)


# End of custom model manager

class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance Suggested'),
        (RATED_R, 'R - Restricted'),
        (RATED_PG, 'PG - Parental Guidance'),
    )
    title = models.CharField(max_length=200)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(to='Person', on_delete=models.SET_NULL, related_name='directed', blank=True, null=True)
    writers = models.ManyToManyField(to='Person', related_name='writing_credits', blank=True)
    actors = models.ManyToManyField(to='Person', through='Role', related_name='acting_credits', blank=True)

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Person(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({} - {})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died
            )

        return '{}, {}, ({})'.format(
            self.last_name,
            self.first_name,
            self.born
        )


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=200)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie', 'person', 'name')


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, u"\U0001F44D"),
        (DOWN, u"\U0001F44E")
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

core/forms.py
from django.contrib.auth import get_user_model
from django import forms
from . models import Movie, Vote, MovieImage


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True)
    movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True)
    value = forms.ChoiceField(label='Vote', widget=forms.RadioSelect, choices=Vote.VALUE_CHOICES)

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True)
    user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True)

    class Meta:
        model = MovieImage
        fields = ('image', 'user', 'movie')

core/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from core.mixins import CachePageVaryOnCookieMixin
from django.shortcuts import redirect
from django.urls import reverse
from core.models import Movie, Person, Vote
from . forms import VoteForm, MovieImageForm
import django


class MovieList(CachePageVaryOnCookieMixin, ListView):
    model = Movie
    paginate_by = 10


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(movie=self.object, user=self.request.user)
            if vote.id:
                vote_form_url = reverse('core:update_vote', kwargs={'movie_id': vote.movie.id, 'pk': vote.id})
            else:
                vote_form_url = reverse('core:create_vote', kwargs={'movie_id': self.object.id})
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_from_url'] = vote_form_url
        return ctx


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:movie_detail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied('You cannot another user vote')
        return vote

    def get_success_url(self):
        movie_id = self.object.id
        return reverse('core:movie_detail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return movie_detail_url


class TopMovies(ListView):
    template_name = 'core/top_movie_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)

        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs

        qs = Movie.objects.top_movies(limit=10)
        cache.set(key, qs)
        return qs

core/templates/core/movie_detail.html
{% extends 'master.html' %}


{% block title %}
   {{ object.title }} - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4">
            <h3>{{ object }}</h3>
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    {% for i in object.movieimage_set.all %}
                        <a href="#" class="thumbnail">
                            <img src="{{ i.image.url }}" alt="...">
                        </a>
                    {% endfor %}
                    
                </div>
            </div>
            <p>{{ object.plot }}</p>
        <p>Directed by {{ object.director }}</p>
        </div>
        <div class="col-md-4">
            <div class="row">
                <div><br>
                    This movie is rated: <br>
                    <span class="label label-primary">{{ object.get_rating_display }}</span>
                </div>
            </div>
            <div class="row">
                {% if vote_form %}
                    <form action="{{ vote_from_url }}" method="post">
                        {% csrf_token %}
                        {{ vote_form.as_p }}
                    <button class="btn btn-primary">Vote</button>
                    </form>
                    <h3>Score: {{ object.score|default_if_none:"No score yet!" }}</h3>
                    {% else %}
                    <p>Login to vote for this movie</p>
                {% endif %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                {% if image_form %}
                     <form action="{% url 'core:movie_image_upload' movie_id=object.id %}" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                         {{ image_form.as_p }}
                        <button class="btn btn-primary">Upload</button>
                     </form>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'master.html' %}

{% block title %} List of Movie | Henrylab {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h1>List of Latest Movies</h1>
            </div>
            <ul class="list-group">
                {% for movie in object_list %}
                    <li class="list-group-item">
                        <a href="{% url 'core:movie_detail' pk=movie.id %}">{{ movie }}</a>
                    </li>

                    {% empty %}
                    <li class="list-group-item">Current, we do not have latest movie!</li>
                {% endfor %}
            </ul>
        <p>Using https? {{ request.is_secure|yesno }}</p>
        {% include 'layouts/pagination.html' %}
        </div>
    </div>
{% endblock %}

core/templates/core/person_detail.html
{% extends 'master.html' %}


{% block title %}
   {{ object.first_name }}  {{ object.last_name }} - {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
       <div class="row">
           <h2>Actor</h2>
              <ul class="list-group">
                   {% for role in object.role_set.all %}
                      <li class="list-group-item">
                          <a href="{% url 'core:movie_detail' role.movie.id %}">{{ role.movie }}</a> {{ role.name }}
                      </li>
                   {% endfor %}
              </ul>
       </div>
        <div class="row">
            <h2>Writer</h2>
            <ul class="list-group">
                {% for movie in object.writing_credits.all %}
                    <li class="list-group-item">
                        <a href="{% url 'core:movie_detail' movie.id %}">{{ movie }}</a>
                    </li>
                {% endfor %}
                
            </ul>
        </div>
        <div class="row">
            <h2>Director</h2>
            <ul class="list-group">
                {% for movie in object.directed.all %}
                    <li class="list-group-item">
                        <a href="{% url 'core:movie_detail' movie.id %}">{{ movie }}</a>
                    </li>
                {% endfor %}
                
            </ul>
        </div>
    </div>
{% endblock %}

core/templates/core/top_movie_list.html
{% extends 'master.html' %}
{% load cache %}

{% block title %} Top Ten Movie | Henrylab {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="page-header">
                <h1>Top Ten Movie as Rated by Users</h1>
            </div>
            <ul class="list-group">
                {% for movie in object_list %}
                    <li class="list-group-item">
                        <a href="{% url 'core:movie_detail' pk=movie.id %}">{{ movie }}</a>
                    </li>

                    {% empty %}
                    <li class="list-group-item">Current, we do not have rated movie!</li>
                {% endfor %}
            </ul>
        {% include 'layouts/pagination.html' %}
        </div>
    </div>
{% endblock %}